<?php

/** Functions page for the Clean Blog WP theme.
 * Please do not edit this file directly.
 *
 */

/**
 * Exit if accessed directly
 */
if ( !defined('ABSPATH')) exit;


/**
 * Variables
 */
$themename = "Clean Blog WP";
$shortname = "cleanblogwp";

/**
 * Include important files:
 * - WP Bootstrap Navwalker
 */
require ( get_template_directory() . '/inc/wp_bootstrap_navwalker.php' );

/**
 * Require WordPress version 3.8 or later
 */
if ( version_compare( $GLOBALS['wp_version'], '3.8-alpha', '<' ) );

/**
 * Set up template defaults
 */
function cleanblog_setup() {

    /**
     * Add HTML5 markup support
     */
    add_theme_support( 'html5', array( 'search-form', 'comment-form', 'comment-list' ) );

    /**
     * Register navigation location(s)
     */
    register_nav_menu( 'primary', __( 'Hoofdmenu', 'cleanblog' ) );
    register_nav_menu( 'sidebar', __( 'Sidebar', 'cleanblog' ) );

    /**
     * Set custom thumbnail sizes
     */
    add_theme_support( 'post-thumbnails' );
    set_post_thumbnail_size( 604, 270, true );
    add_image_size('Single Top', 848, 250, true);
}
add_action( 'after_setup_theme', 'cleanblog_setup' );

/**
 * Add Bootstrap support, add jquery and make room for the WordPress navbar by
 * moving the body down.
 */
function skematik_jquery_js(){
    wp_enqueue_script('jquery');
}

function wpt_register_js() {
    wp_register_script(
        'jquery.bootstrap.min',
        get_template_directory_uri() . '/js/bootstrap.min.js',
        'jquery'
    );
    wp_enqueue_script('jquery.bootstrap.min');
}

add_action( 'wp_enqueue_scripts', 'skematik_jquery_js' );
add_action( 'wp_enqueue_scripts', 'wpt_register_js' );

function mbe_wp_head(){
    echo '<style>'.PHP_EOL;
    echo 'body{ padding-top: 70px !important; }'.PHP_EOL;
    // Using custom CSS class name.
    echo 'body.body-logged-in .navbar-fixed-top{ top: 28px !important; }'.PHP_EOL;
    // Using WordPress default CSS class name.
    echo 'body.logged-in .navbar-fixed-top{ top: 28px !important; }'.PHP_EOL;
    echo '</style>'.PHP_EOL;
}